/* outputtest2.sas */
DATA CRD;
INPUT FACTOR YIELD1-YIELD4;
YIELD = YIELD1; OUTPUT;
YIELD = YIELD2; OUTPUT;
YIELD = YIELD3; OUTPUT;
YIELD = YIELD4; OUTPUT;
DROP YIELD1 - YIELD4;
CARDS;
1 2 3 4 6
2 3 5 6 7
3 3 4 5 6
;
PROC PRINT DATA=CRD;
VAR FACTOR YIELD;
RUN;
